### ISSUE TITLE
Discontinue this package?

### ISSUE THREAD

**Issue by kevmoo** [dart-lang/package_resolver#18]
Now that we have *one* way to do things, should we deprecate the whole thing and tell folks to use the SDK apis directly?

@lrhn @nex3 ?

**Comment by nex3** [comment]
The SDK APIs don't have any way of representing a package config as a first-class object, or of providing synchronous access to it. We still need this package for Dart Sass, for example, so that users can pass in a different package config than the isolate's native one do resolve `package:` imports.
